### PR TITLE
the package was made for windows!!

### PR DESCRIPTION
**Pull request by JonnycatMeow**

### CODE REVIEW

**Review by Vortex2Oblivion — CHANGES_REQUESTED** [review]
You also need to edit the include.xml for windows too

**Comment by JonnycatMeow** [comment]
idk how to accept the change for the file

**Comment by Vortex2Oblivion** [comment]
> idk how to accept the change for the file 

Just make another commit changing the thing and it will get added to the pr

**Comment by JonnycatMeow** [comment]
fixed it

**Pull request merged**
